version: "3"
services:
  proxy:
    image: 'nginx:alpine'
    ports:
      - 8080:8080
    volumes:
      - ./frontend/dist:/frontend/dist:ro
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: "1m"

  backend:
    image: 'python:alpine'
    volumes:
      - ./backend/app.py:/app.py:ro
    command:
      - 'sh'
      - '-c'
      - 'pip install flask && python /app.py'
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: "1m"
